lista=[]
fatturatoN=float(input("A quanto corrisponde il fatturato della zona NORD "))
fatturatoC=float(input("A quanto corrisponde il fatturato della zona CENTRO "))
fatturatoS=float(input("A quanto corrisponde il fatturato della zona SUD "))
fatturatoI=float(input("A quanto corrisponde il fatturato della zona ISOLE "))
lista.append(fatturatoN)
lista.append(fatturatoC)
lista.append(fatturatoS)
lista.append(fatturatoI)
totale=sum(lista)
print("Il fatturato totale è",totale)
print("Il valore in percentuale del NORD rispetto al totale è",fatturatoN*100/totale)
print("Il valore in percentuale del CENTRO rispetto al totale è",fatturatoC*100/totale)
print("Il valore in percentuale del SUD rispetto al totale è",fatturatoS*100/totale)
print("Il valore in percentuale delle ISOLE rispetto al totale è",fatturatoI*100/totale)